services:
  relay_alice:
    environment:
      - ${RUST_LOG:-info}
    image: ${RELAYCHAIN_DOCKER_IMAGE:-parity/polkadot:v0.9.24}
    user: root
    entrypoint: ""
    command: >
      bash -xec "
      /usr/bin/polkadot  build-spec --chain ${RELAY_CHAIN:-rococo-local} --disable-default-bootnode --raw > /etc/mangata/rococo-local-0.9.24.json
      "
    volumes:
      - ./config:/etc/mangata
    ports:
      - 9944:9944
      - 30333:30333