[package]
name = "mangata-node"
version = "0.1.0"
authors = ["Mangata Team"]
edition = "2018"
license = "Unlicense"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }

[[bin]]
name = "mangata-node"
path = "bin/main.rs"

[features]
default = ['mangata-kusama']
mangata-kusama = [
		"mangata-kusama-runtime/std",
		"xyk-rpc/std",
]
mangata-rococo = [
		"mangata-rococo-runtime/std",
		"xyk-rpc/std",
]
disable-execution = ['mangata-kusama-runtime/disable-execution']
runtime-benchmarks = ["mangata-kusama-runtime/runtime-benchmarks", "polkadot-cli/runtime-benchmarks"]
try-runtime = ["mangata-kusama-runtime/try-runtime", "mangata-rococo-runtime/try-runtime"]

[dependencies]
derive_more = "0.99.2"
log = "0.4.14"
codec = { package = "parity-scale-codec", version = "2.0.0" }
clap = { version = "3.1", features = ["derive"] }
serde = { version = "1.0.119", features = ["derive"] }
hex-literal = "0.3.4"
hex = "0.4.0"

# RPC related Dependencies
jsonrpc-core = "18.0.0"

# Local Dependencies
mangata-kusama-runtime = { path = "../runtime/mangata-kusama/", optional = true }
mangata-rococo-runtime = { path = "../runtime/mangata-rococo/", optional = true }
mangata-primitives = { path = "../primitives/mangata/"}

# Substrate Dependencies
frame-benchmarking = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
frame-benchmarking-cli = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
try-runtime-cli = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }

pallet-transaction-payment-rpc = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }

substrate-frame-rpc-system = { package = "mangata-rpc-nonce", path = "../rpc/nonce" }
substrate-prometheus-endpoint = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }

## Substrate Client Dependencies
sc-basic-authorship-ver = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-chain-spec = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-cli = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-client-api = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-consensus = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-executor = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-network = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-keystore = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-rpc = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-rpc-api = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-service = { git = "https://github.com/mangata-finance/substrate", features = ["wasmtime"], branch = "mangata-dev-v0.9.17" }
sc-consensus-aura = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-finality-grandpa = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-telemetry = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-transaction-pool = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-transaction-pool-api = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sc-tracing = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }

## Substrate Primitive Dependencies
sp-api = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-block-builder = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-blockchain = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-consensus = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-consensus-aura = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-core = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-inherents = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-keystore = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-offchain = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-runtime = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-session = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-timestamp = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-transaction-pool = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
ver-api = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-storage = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-trie = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }


# Cumulus dependencies
cumulus-client-cli = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }
# cumulus-client-collator = { git = 'https://github.com/mangata-finance/cumulus', branch = mangata-dev-v0.9.17' }
cumulus-client-consensus-aura = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }
cumulus-client-consensus-common = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }
cumulus-client-network = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }
cumulus-client-service = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }
cumulus-primitives-core = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }
cumulus-primitives-parachain-inherent = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }
cumulus-relay-chain-interface = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }
cumulus-relay-chain-local = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17' }


# Polkadot dependencies
polkadot-cli = { git = "https://github.com/mangata-finance/polkadot", branch = "mangata-dev-v0.9.17" }
polkadot-parachain = { git = "https://github.com/mangata-finance/polkadot", branch = "mangata-dev-v0.9.17" }
polkadot-primitives = { git = "https://github.com/mangata-finance/polkadot", branch = "mangata-dev-v0.9.17" }
polkadot-service = { git = "https://github.com/mangata-finance/polkadot", branch = "mangata-dev-v0.9.17" }
polkadot-test-service = { git = "https://github.com/mangata-finance/polkadot", branch = "mangata-dev-v0.9.17" }


# Mangata dependencies
xyk-rpc = { default-features = false, version = '2.0.0', path = '../pallets/xyk/rpc' }
xyk-runtime-api = { default-features = false, version = '2.0.0', path = '../pallets/xyk/runtime-api' }

# Snowbridge dependencies
artemis-core = {default-features = false, version = "0.1.1", git = "https://github.com/mangata-finance/snowbridge", branch = "mangata-dev-v0.9.17"}


[dev-dependencies]
sub-tokens = { git = "https://github.com/paritytech/substrate-debug-kit", branch = "master" }
criterion = { version = "0.3.5", features = [ "async_tokio", "html_reports" ] }
sc-block-builder = { package="sc-block-builder-ver", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
sp-keyring = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
tokio = { version = "1.15", features = ["macros", "time"] }
pallet-timestamp = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev-v0.9.17" }
sp-tracing = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
frame-system = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
pallet-transaction-payment = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
frame-system-rpc-runtime-api = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
cumulus-pallet-parachain-system = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17'}
cumulus-test-relay-sproof-builder = { git = 'https://github.com/mangata-finance/cumulus', branch = 'mangata-dev-v0.9.17'}
polkadot-runtime-common = { git = "https://github.com/mangata-finance/polkadot", branch = "mangata-dev-v0.9.17" }
sp-consensus-slots = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17" }
futures = "0.3.16"
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false}
sp-core = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17", features = ["full_crypto"]}
extrinsic-shuffler = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev-v0.9.17"}
cfg-if = "1.0.0"

[[bench]]
name = "block_production"
harness = false
